version: '3.4'

services:
  JavJun:
    image: ${DOCKER_REGISTRY-}javjun
    container_name: students.app
    build:
      context: .
      dockerfile: Dockerfile
  students-db:
    image: mysql:latest
    container_name: students.db
    environment:
      - MYSQL_ROOT_PASSWORD=pePLiy25
      - MYSQL_DATABASE=studentsDB
    volumes:
      - ./.containers/database:/var/lib/mysql
    ports:
      - 3311:3306